bubblesort.settings:
  type: config_object
  label: 'Bubblesort settings'
  mapping:
    integers_needed:
      type: string
      label: 'Integers needed'
    integer_min:
      type: string
      label: 'Minimum integer'
    integer_max:
      type: string
      label: 'Maximum integer'